from pathlib import Path
import os, json, re, shutil, html
from urllib.parse import urlparse
from content import articles

ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'dist'
OUT.mkdir(exist_ok=True)
SITE_URL=os.environ.get('SITE_URL','').rstrip('/')
if os.environ.get('DEPLOYMENT_BUILD')=='true' and not SITE_URL:
    raise SystemExit('Deployment requires the actual SITE_URL; refusing to publish a noindex preview.')
if SITE_URL:
    parsed=urlparse(SITE_URL)
    if parsed.scheme!='https' or not parsed.netloc or parsed.query or parsed.fragment or parsed.username:
        raise SystemExit('SITE_URL must be an HTTPS origin with an optional project path, without credentials, query or fragment.')
BASE=urlparse(SITE_URL).path.rstrip('/') if SITE_URL else ''
CONTACT=os.environ.get('CONTACT_EMAIL','')
if CONTACT and not re.fullmatch(r'[A-Za-z0-9.!#$%&\x27*+/=?^_`{|}~-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}', CONTACT):
    raise SystemExit('CONTACT_EMAIL is invalid')
PUBLISHER=os.environ.get('ADSENSE_PUBLISHER_ID','')
VERIFY=os.environ.get('GOOGLE_SITE_VERIFICATION','')
if PUBLISHER and not re.fullmatch(r'ca-pub-\d{16}',PUBLISHER):
    raise SystemExit('ADSENSE_PUBLISHER_ID must be a real ca-pub ID with 16 digits')
ADS=os.environ.get('ADS_ENABLED','false')=='true'
AUTO_ADS=os.environ.get('AUTO_ADS_ENABLED','false')=='true'
AD_TAG=ADS or AUTO_ADS
if AD_TAG and (not PUBLISHER or os.environ.get('ADS_PRIVACY_READY')!='true'):
    raise SystemExit('AdSense integration requires a publisher ID and a verified, published consent setup (ADS_PRIVACY_READY=true).')
SLOT=os.environ.get('ADSENSE_SLOT_ID','')
if ADS and (not PUBLISHER or not re.fullmatch(r'\d+',SLOT) or os.environ.get('ADS_PRIVACY_READY')!='true' or not CONTACT):
    raise SystemExit('Live ads require publisher and slot IDs, a contact email, and ADS_PRIVACY_READY=true after configuring required consent in AdSense.')
for old in OUT.iterdir():
    if old.is_dir():shutil.rmtree(old)
    else:old.unlink()
for name in ['style.css','app.mjs','dates.mjs','privacy-controls.js']:
    shutil.copyfile(ROOT/'src'/name,OUT/name)
e=html.escape
def link(path):return BASE+'/'+path
def langpath(path,hi):return ('hi/' if hi else '')+path
favicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="11" fill="#082c43"/><text x="9" y="29" font-family="Arial,sans-serif" font-size="29" font-weight="bold" fill="#c8f1e8">R</text></svg>'
from urllib.parse import quote
favicon_url='data:image/svg+xml,'+quote(favicon,safe='')
pages=[]
def ad():
    if not ADS:return ''
    return f'<aside class="ad-unit" aria-label="Advertisement"><span>Advertisement</span><ins class="adsbygoogle" style="display:block" data-ad-client="{PUBLISHER}" data-ad-slot="{SLOT}" data-ad-format="auto" data-full-width-responsive="true"></ins></aside>'
def shell(path,title,desc,body,hi=False,kind='WebPage',index=True):
    lang='hi' if hi else 'en'
    home=link(langpath('',hi))
    alternate=path[3:] if hi else 'hi/'+path
    pair=path[3:] if hi else path
    canonical=f'<link rel="canonical" href="{e(SITE_URL+"/"+path)}"><link rel="alternate" hreflang="en" href="{e(SITE_URL+"/"+pair)}"><link rel="alternate" hreflang="hi" href="{e(SITE_URL+"/hi/"+pair)}"><link rel="alternate" hreflang="x-default" href="{e(SITE_URL+"/"+pair)}">' if SITE_URL and index else ''
    robots='index,follow,max-image-preview:large' if SITE_URL and index else 'noindex,follow'
    schema={'@context':'https://schema.org','@type':kind,'name':title,'description':desc,'inLanguage':lang}
    if SITE_URL:schema['url']=SITE_URL+'/'+path
    if kind=='WebApplication':schema.update({'applicationCategory':'UtilitiesApplication','operatingSystem':'Any','isAccessibleForFree':True,'browserRequirements':'Requires JavaScript for calculations'})
    metadata=(f'<meta name="google-site-verification" content="{e(VERIFY)}">' if VERIFY else '')+(f'<meta name="google-adsense-account" content="{PUBLISHER}">' if PUBLISHER else '')
    ads_script=f'<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={PUBLISHER}" crossorigin="anonymous"></script>' if AD_TAG and index else ''
    consent_control=('<button type="button" data-privacy-settings hidden style="font:inherit;color:inherit;background:transparent;border:0;padding:0;text-decoration:underline;cursor:pointer">'+('गोपनीयता और कुकी सेटिंग' if hi else 'Privacy & cookie settings')+'</button><script src="'+link('privacy-controls.js')+'" defer></script>') if AD_TAG and index else ''
    footer_names=[('about/','हमारे बारे में' if hi else 'About'),('contact/','संपर्क' if hi else 'Contact'),('privacy/','गोपनीयता' if hi else 'Privacy'),('terms/','शर्तें व अस्वीकरण' if hi else 'Terms & disclaimer')]
    footerlinks=''.join(f'<a href="{link(langpath(p,hi))}">{n}</a>' for p,n in footer_names)
    content=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="robots" content="{robots}"><meta name="theme-color" content="#082c43">{canonical}<meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:locale" content="{'hi_IN' if hi else 'en_IN'}">{f'<meta property="og:url" content="{e(SITE_URL+"/"+path)}">' if SITE_URL else ''}<meta name="twitter:card" content="summary"><meta name="twitter:title" content="{e(title)}"><meta name="twitter:description" content="{e(desc)}">{metadata}<link rel="icon" type="image/svg+xml" href="{favicon_url}"><link rel="stylesheet" href="{link('style.css')}"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False).replace('<','&lt;')}</script><script type="module" src="{link('app.mjs')}"></script>{ads_script}</head>
<body><a class="skip" href="#main">{'मुख्य सामग्री पर जाएँ' if hi else 'Skip to content'}</a><header class="site-header"><nav class="nav wrap" aria-label="{'मुख्य नेविगेशन' if hi else 'Main navigation'}"><a class="brand" href="{home}" aria-label="RailDate home"><span class="brand-mark" aria-hidden="true">R</span><span>Rail<span>Date</span></span></a><div class="nav-links"><a class="active" href="{home}">{'कैलकुलेटर' if hi else 'Calculator'}</a><a class="guide-nav" href="{home}#guides">{'बुकिंग गाइड' if hi else 'Booking guides'}</a><a class="language" href="{link(alternate)}" lang="{'en' if hi else 'hi'}" hreflang="{'en' if hi else 'hi'}">{'English' if hi else 'हिन्दी'}</a></div></nav></header>
<div class="today-strip"><div class="wrap today-content"><span>{'आज' if hi else 'Today'}: <strong id="today-date">{'लोड हो रहा है' if hi else 'Loading date'}</strong> &nbsp;·&nbsp; <span id="ist-clock" class="clock">IST</span></span><span>{'सामान्य विंडो में ट्रेन की शुरुआत' if hi else 'Standard window · train departures through'} <strong id="window-date">—</strong></span></div></div>
<main id="main" class="wrap">{body}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div class="footer-brand"><a class="brand" href="{home}">Rail<span>Date</span></a><p>{'यात्रा की तैयारी सही तारीख से। स्वतंत्र कैलकुलेटर; IRCTC या भारतीय रेल से संबद्ध नहीं।' if hi else 'A little planning. A smoother journey. An independent calculator, not affiliated with IRCTC or Indian Railways.'}</p></div><div class="footer-links">{footerlinks}{consent_control}<a href="https://www.irctc.co.in/nget/train-search" rel="external">{'आधिकारिक IRCTC ↗' if hi else 'Official IRCTC ↗'}</a></div></div><div class="footer-bottom"><span>© 2026 RailDate</span><span>{'सभी समय भारतीय मानक समय (IST) में।' if hi else 'All booking times are in Indian Standard Time (IST).'}</span></div></div></footer>{'<script src="'+link('ads.js')+'" defer></script>' if ADS else ''}</body></html>'''
    destination=OUT/(path+'index.html') if index else OUT/path
    destination.parent.mkdir(parents=True,exist_ok=True);destination.write_text(content,encoding='utf-8')
    if index:pages.append(path)

def guides(hi):
    data=[('advance-booking-guide/','01 · ADVANCE BOOKING' if not hi else '01 · अग्रिम बुकिंग','The 60-day rule, explained' if not hi else '60 दिन का नियम समझें','Count calendar days, handle month changes, and know the exceptions.' if not hi else 'महीना बदलने पर भी सही गणना करें और अपवाद जानें.'),('tatkal-booking-guide/','02 · TATKAL' if not hi else '02 · तत्काल','Get your Tatkal timing right' if not hi else 'तत्काल का सही समय जानें','Understand the date, AC and non-AC opening times, and what to prepare.' if not hi else 'बुकिंग तारीख, AC और Non-AC का समय तथा तैयारी जानें।'),('train-origin-date-guide/','03 · JOURNEY PLANNING' if not hi else '03 · यात्रा की तैयारी','Boarding on day two?' if not hi else 'दूसरे दिन ट्रेन पकड़ रहे हैं?','Your boarding date and the train’s starting date can be different.' if not hi else 'आपकी यात्रा और ट्रेन की शुरुआत अलग तारीखों पर हो सकती हैं।')]
    return '<div class="guide-grid">'+''.join(f'<a class="guide-card" href="{link(langpath(p,hi))}"><span class="number">{num}</span><h3>{title}</h3><p>{text}</p><span class="read">{"गाइड पढ़ें" if hi else "Read guide"} ↗</span></a>' for p,num,title,text in data)+'</div>'
def home(hi):
    t=lambda en,hn:hn if hi else en
    options=''.join(f'<option value="{i}">{t("Day "+str(i+1)+(" · same date as origin" if i==0 else " · "+str(i)+" day"+("s" if i>1 else "")+" after origin"),"दिन "+str(i+1)+(" · शुरुआत वाली तारीख" if i==0 else " · शुरुआत के "+str(i)+" दिन बाद"))}</option>' for i in range(7))
    faq=[(t('Does this calculator book a ticket?','क्या यह टिकट बुक करता है?'),t('No. It calculates the opening date and lets you download a calendar reminder. Use IRCTC to check seats and complete your booking.','नहीं। यह बुकिंग खुलने की तारीख निकालता है और कैलेंडर रिमाइंडर देता है। सीट जाँचने और टिकट बुक करने के लिए IRCTC इस्तेमाल करें।')),(t('Are 60 days the same as two months?','क्या 60 दिन का मतलब दो महीने है?'),t('No. Calendar months have different lengths. Subtract 60 calendar days from the train’s departure date at its starting station.','नहीं। महीनों में दिनों की संख्या अलग होती है। ट्रेन की शुरुआती स्टेशन वाली तारीख से 60 कैलेंडर दिन घटाएँ।')),(t('What if I board after midnight on the next day?','अगर मैं अगली रात के बाद ट्रेन पकड़ूँ?'),t('Choose your actual boarding date and select Day 2 when the train starts the previous day. Check the timetable to confirm the day number.','अपनी असली बोर्डिंग तारीख चुनें। ट्रेन पिछले दिन शुरू हुई हो तो दिन 2 चुनें। समय-सारणी से दिन संख्या जाँचें।')),(t('Does “opening time has passed” mean seats are available?','क्या बुकिंग खुलने का मतलब सीट मिलना है?'),t('No. The opening time is a date calculation, not live availability. Seats, quotas, chart preparation and booking cut-offs must be checked on IRCTC.','नहीं। यह सिर्फ तारीख की गणना है, लाइव सीट उपलब्धता नहीं। सीट, कोटा, चार्ट और बुकिंग बंद होने का समय IRCTC पर जाँचें।')),(t('Will the reminder notify me automatically?','क्या रिमाइंडर अपने आप सूचना भेजेगा?'),t('Download the .ics file and import it into your calendar. It includes an alert 15 minutes before opening; whether it rings depends on your calendar’s permissions and settings.','डाउनलोड की गई .ics फ़ाइल अपने कैलेंडर में जोड़ें। इसमें 15 मिनट पहले का अलर्ट है; सूचना आपके कैलेंडर की सेटिंग और अनुमति पर निर्भर है।'))]
    body=f'''<section class="intro"><div class="eyebrow">{t('TRAIN BOOKING, BETTER PLANNED','ट्रेन बुकिंग की सही तैयारी')}</div><h1>{t('Train booking date calculator.','ट्रेन टिकट बुकिंग तारीख कैलकुलेटर।')}</h1><p>{t('IRCTC 60-day advance & Tatkal booking date calculator. Pick your journey date to get started.','IRCTC 60 दिन अग्रिम और तत्काल बुकिंग तारीख कैलकुलेटर। अपनी यात्रा की तारीख चुनें।')}</p></section>
<section class="calculator" aria-label="{t('Train booking date calculator','ट्रेन बुकिंग तारीख कैलकुलेटर')}"><div class="input-panel"><form id="booking-form" novalidate><div class="segmented" role="group" aria-label="{t('Booking type','बुकिंग प्रकार')}"><button type="button" data-mode="advance" aria-pressed="true">{t('Advance · 60 days','अग्रिम · 60 दिन')}</button><button type="button" data-mode="tatkal" aria-pressed="false">{t('Tatkal · 1 day','तत्काल · 1 दिन')}</button></div><div class="field"><label for="journey">{t('Your journey date','आपकी यात्रा की तारीख')}</label><input id="journey" name="journey" type="date" required aria-describedby="date-hint error"><p class="hint" id="date-hint">{t('The date you will board the train.','जिस तारीख को आप ट्रेन में चढ़ेंगे।')}</p></div><div class="field"><label for="boarding-day">{t('Which day of the train’s journey do you board?','ट्रेन की यात्रा के किस दिन आप चढ़ेंगे?')}</label><select name="boarding-day" id="boarding-day" aria-describedby="boarding-hint">{options}</select><p class="hint" id="boarding-hint">{t('Check the timetable. Day 1 is the train’s starting date.','समय-सारणी जाँचें। दिन 1 ट्रेन की शुरुआती तारीख है।')}</p></div><div class="field" id="class-field" hidden><label for="travel-class">{t('Travel class','यात्रा श्रेणी')}</label><select id="travel-class" name="travel-class"><option value="ac">AC · 10:00 AM IST</option><option value="nonac">Non-AC · 11:00 AM IST</option></select></div><p class="error" id="error" role="alert"></p><button class="primary calculate" type="submit">{t('Find my booking date','बुकिंग की तारीख देखें')} <span aria-hidden="true">→</span></button><p class="privacy-note">{t('No login. No passenger details. Just your date.','न लॉगिन, न यात्री की जानकारी। सिर्फ आपकी तारीख।')}</p></form><noscript><p class="offline">{t('Enable JavaScript for the calculator. You can still read the booking guides below.','कैलकुलेटर के लिए JavaScript चालू करें। नीचे गाइड पढ़ सकते हैं।')}</p></noscript></div>
<div class="result-panel" id="result-panel"><div class="result-top"><span>{t('YOUR BOOKING WINDOW','आपकी बुकिंग विंडो')}</span><span class="result-tag" id="result-type">60-day advance</span></div><div class="ticket-result" aria-live="polite" aria-atomic="true"><p>{t('Booking opening date','बुकिंग खुलने की तारीख')}</p><div class="date-result" id="opening-date">—</div><p id="opening-weekday">{t('Choose a journey date','यात्रा तारीख चुनें')}</p><div class="time-result" id="opening-time">08:00 AM IST</div><div class="status-pill" id="status">{t('Calculated in Indian Standard Time','भारतीय मानक समय में गणना')}</div></div><dl class="ticket-details"><div><dt>{t('YOUR JOURNEY','आपकी यात्रा')}</dt><dd id="journey-result">—</dd></div><div><dt>{t('TRAIN STARTS','ट्रेन की शुरुआत')}</dt><dd id="origin-result">—</dd></div></dl><div class="result-actions"><button class="secondary" id="reminder" type="button" disabled>{t('Calendar reminder','कैलेंडर रिमाइंडर')}</button><button class="secondary" id="copy" type="button" disabled>{t('Copy date','तारीख कॉपी करें')}</button></div><p id="action-message" class="live-note" role="status"></p><p class="result-note">{t('Planning reference only. Seat availability is checked on IRCTC.','केवल योजना के लिए। सीट उपलब्धता IRCTC पर जाँचें।')}</p></div></section>
<aside class="notice"><span class="notice-icon" aria-hidden="true">ⓘ</span><span><strong>{t('One detail makes a difference.','एक बात याद रखें।')}</strong> {t('The calculation uses the train’s starting date, not just your boarding date. Some trains and quotas have a different booking window.','गणना ट्रेन की शुरुआत वाली तारीख से होती है। कुछ ट्रेनों और कोटा की बुकिंग विंडो अलग होती है।')} <a href="{link(langpath('train-origin-date-guide/',hi))}">{t('See an example','उदाहरण देखें')}</a></span></aside>
{ad()}<section id="guides"><div class="section-head"><div><h2>{t('A little know-how goes a long way.','सही जानकारी, बेहतर तैयारी।')}</h2><p>{t('Simple answers for your next train journey.','अगली ट्रेन यात्रा के लिए आसान जानकारी।')}</p></div></div>{guides(hi)}</section>
<section class="explainer"><div><div class="eyebrow">{t('FROM DATE TO DEPARTURE','तारीख से यात्रा तक')}</div><h2>{t('Your plan, in three simple steps.','तीन आसान कदमों में तैयारी।')}</h2><p>{t('Plan ahead without sharing passenger information. The calculator runs in your browser.','यात्री की निजी जानकारी दिए बिना योजना बनाएँ। गणना आपके ब्राउज़र में होती है।')}</p></div><ol class="steps"><li><span>01</span><div><strong>{t('Pick your boarding date','बोर्डिंग तारीख चुनें')}</strong><p>{t('Use your ticket’s journey date and the correct day from the train timetable.','यात्रा की तारीख और ट्रेन समय-सारणी से सही दिन संख्या चुनें।')}</p></div></li><li><span>02</span><div><strong>{t('Check the opening date','बुकिंग खुलने की तारीख देखें')}</strong><p>{t('Switch between advance booking and Tatkal. All times are shown in IST.','अग्रिम या तत्काल चुनें। सभी समय IST में दिखेंगे।')}</p></div></li><li><span>03</span><div><strong>{t('Save a calendar reminder','कैलेंडर रिमाइंडर सेव करें')}</strong><p>{t('Import the downloaded event, then book directly on the official IRCTC website.','डाउनलोड किया इवेंट कैलेंडर में जोड़ें, फिर आधिकारिक IRCTC पर बुक करें।')}</p></div></li></ol></section>
<section class="faq-section"><h2>{t('Before you book','बुकिंग से पहले')}</h2>{''.join('<details><summary>'+q+'</summary><p>'+a+'</p></details>' for q,a in faq)}<p class="source-note">{t('Rules reviewed: 13 September 2026. Sources:','नियम जाँचे: 13 सितंबर 2026। स्रोत:')} <a href="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2065879">{t('Railways ARP announcement','रेलवे ARP सूचना')}</a><a href="https://contents.irctc.co.in/en/TatkalFaq.html">IRCTC Tatkal FAQ</a></p></section>'''
    shell(langpath('',hi),t('Train Booking Date Calculator — IRCTC 60 Days & Tatkal | RailDate','IRCTC 60 दिन अग्रिम व तत्काल बुकिंग तारीख कैलकुलेटर | RailDate'),t('Calculate your train ticket booking opening date with the 60-day IRCTC rule or Tatkal timings. Supports train-origin day adjustments and calendar reminders.','यात्रा तारीख से IRCTC 60 दिन अग्रिम और तत्काल बुकिंग की तारीख निकालें। ट्रेन की शुरुआत का दिन चुनें और कैलेंडर रिमाइंडर डाउनलोड करें।'),body,hi,'WebApplication')

for hi in [False,True]:
    home(hi)
    for item in articles(hi,CONTACT,AD_TAG,PUBLISHER):
        path,title,desc,content=item
        related=''.join(f'<a href="{link(langpath(p,hi))}">{name}</a>' for p,name in [('advance-booking-guide/','60 दिन का नियम' if hi else 'The 60-day booking rule'),('tatkal-booking-guide/','तत्काल बुकिंग' if hi else 'Tatkal booking'),('train-origin-date-guide/','ट्रेन की शुरुआती तारीख' if hi else 'Your train’s starting date')])
        body=f'<div class="article-shell"><article class="article"><div class="breadcrumb"><a href="{link(langpath("",hi))}">{"कैलकुलेटर" if hi else "Calculator"}</a> / {e(title)}</div><div class="eyebrow">{"RAILDATE · जानकारी" if hi else "RAILDATE · THE PLANNING NOTES"}</div><h1>{e(title)}</h1><p class="lead">{e(desc)}</p><div class="article-meta">{"RailDate द्वारा · 13 सितंबर 2026 को समीक्षा" if hi else "By RailDate · Reviewed 13 September 2026"}</div>{content}{ad()}</article><aside class="aside"><h2>{"अपनी यात्रा की तैयारी करें" if hi else "Plan your journey"}</h2>{related}<a class="primary" href="{link(langpath("",hi))}">{"कैलकुलेटर खोलें" if hi else "Open calculator"} →</a></aside></div>'
        shell(langpath(path,hi),title+' | RailDate',desc,body,hi)
for hi in [False,True]:
    shell('hi/404.html' if hi else '404.html','Page not found | RailDate','This page could not be found.',f'<section class="page-404"><div class="eyebrow">404 · RAILDATE</div><h1>{"यह पेज नहीं मिला।" if hi else "This stop doesn’t exist."}</h1><p>{"सही बुकिंग तारीख जानने के लिए कैलकुलेटर पर वापस जाएँ।" if hi else "Head back to the calculator to find your booking date."}</p><a class="primary" href="{link(langpath("",hi))}">{"कैलकुलेटर पर जाएँ" if hi else "Back to calculator"}</a></section>',hi,index=False)
if SITE_URL:
    (OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+e(SITE_URL+'/'+p)+'</loc></url>' for p in pages)+'</urlset>')
(OUT/'robots.txt').write_text('User-agent: *\n'+('Allow: /\nSitemap: '+SITE_URL+'/sitemap.xml\n' if SITE_URL else 'Disallow: /\n'))
if PUBLISHER:(OUT/'ads.txt').write_text(f'google.com, {PUBLISHER.removeprefix("ca-")}, DIRECT, f08c47fec0942fa0\n')
if ADS:(OUT/'ads.js').write_text('document.querySelectorAll(".adsbygoogle").forEach(()=>{try{(window.adsbygoogle=window.adsbygoogle||[]).push({});}catch{}});')
(OUT/'.nojekyll').touch()
print(f'Built {len(pages)} indexable routes and two 404 pages. Canonical origin: {SITE_URL or "unset (noindex preview)"}. AdSense tag: {"installed (approval required)" if AD_TAG else "off"}.')
