from html import escape

ARP='https://www.pib.gov.in/PressReleasePage.aspx?PRID=2065879'
TATKAL='https://contents.irctc.co.in/en/TatkalFaq.html'
ORIGIN='https://www.pmf.irctc.co.in/cn/TermsAndConditions.html'
AUTH='https://www.pib.gov.in/PressReleasePage.aspx?PRID=2135694'

def articles(hi,email,ads,publisher):
    contact=f'<a href="mailto:{escape(email)}">{escape(email)}</a>' if email else '<a href="https://github.com/yashwant-verma">github.com/yashwant-verma</a>'
    if hi:
        return [
        ('advance-booking-guide/','60 दिन पहले ट्रेन टिकट कब बुक होगा?','कैलेंडर दिनों की गणना, बुकिंग का समय और वे स्थितियाँ जहाँ सामान्य नियम लागू नहीं होता।',f'''
<h2>60 दिन का नियम</h2><p>सामान्य अग्रिम आरक्षण अवधि 60 दिन है; यात्रा का दिन इसमें शामिल नहीं होता। इसे दो कैलेंडर महीने समझकर तारीख न चुनें। यह व्यवस्था 1 नवंबर 2024 से लागू हुई। <a href="{ARP}">रेल मंत्रालय की सूचना</a> में कुछ दिन की एक्सप्रेस ट्रेनों के लिए कम अवधि और विदेशी पर्यटक कोटा के अलग नियम भी दिए गए हैं।</p>
<h2>तारीख कैसे निकालें?</h2><ol><li>ट्रेन की शुरुआती स्टेशन से चलने की तारीख पता करें।</li><li>उस तारीख से 60 दिन घटाएँ।</li><li>सामान्य opening-day बुकिंग का समय सुबह 8 बजे IST मानें और ट्रेन का कोटा IRCTC पर जाँचें।</li></ol>
<div class="example"><strong>उदाहरण: ट्रेन 10 नवंबर 2026 को शुरू होती है</strong><p>10 नवंबर में से 60 दिन घटाने पर 11 सितंबर 2026 आता है। सामान्य बुकिंग सुबह 8 बजे IST से खुलने की गणना होगी। केवल दो महीने घटाने पर 10 सितंबर आता, जो एक दिन पहले है।</p></div>
<h2>कैलेंडर बदलने पर</h2><p>तारीख घटाने में महीनों की लंबाई और लीप वर्ष का फर्क पड़ता है। RailDate कैलेंडर दिनों की गणना करता है। उदाहरण के लिए 30 अप्रैल 2027 से 60 दिन पहले 1 मार्च 2027 है। हाथ से गिनते समय महीने बदलने पर गलती हो सकती है।</p>
<h2>सुबह 8 बजे से पहले आज की विंडो</h2><p>आज से 60वें दिन की नई तारीख सुबह 8 बजे जुड़ती है। उससे पहले कैलकुलेटर की ऊपरी पट्टी पिछली खुली सामान्य सीमा दिखाती है। यह सीट उपलब्धता नहीं बताती।</p>
<h2>गणना की सीमाएँ</h2><p>यह सामान्य ARP कैलकुलेटर है। विशेष ट्रेन, अलग कोटा या छोटी आरक्षण अवधि पर नियम बदल सकते हैं। किसी गाड़ी में सीट मिलना, बुकिंग बंद होना या चार्ट बनना इस परिणाम से नहीं पता चलता। आधिकारिक बुकिंग स्क्रीन अंतिम जाँच है।</p>
<p><a href="{ORIGIN}">IRCTC opening-day समय और शुरुआती स्टेशन की परिभाषा</a> देखें। उस पुराने पेज पर 120 दिन का उल्लेख है; अवधि के लिए ऊपर दी गई नई 60 दिन की सूचना लागू की गई है।</p>'''),
        ('tatkal-booking-guide/','तत्काल टिकट की तारीख और समय','AC और Non-AC के अलग समय तथा ट्रेन की शुरुआती तारीख का असर समझें।',f'''
<h2>तत्काल कब खुलता है?</h2><p>तत्काल की गणना ट्रेन के शुरुआती स्टेशन से चलने की तारीख के एक दिन पहले होती है। AC के लिए सुबह 10 बजे और Non-AC के लिए सुबह 11 बजे IST opening time है। हर ट्रेन, श्रेणी या स्टेशन जोड़ी में तत्काल कोटा हो, यह जरूरी नहीं। <a href="{TATKAL}">आधिकारिक IRCTC तत्काल FAQ</a></p>
<div class="table-wrap"><table><thead><tr><th>विकल्प</th><th>दिन</th><th>समय IST</th></tr></thead><tbody><tr><td>AC तत्काल</td><td>शुरुआती तारीख से 1 दिन पहले</td><td>10:00 AM</td></tr><tr><td>Non-AC तत्काल</td><td>शुरुआती तारीख से 1 दिन पहले</td><td>11:00 AM</td></tr></tbody></table></div>
<div class="example"><strong>11 सितंबर को यात्रा, ट्रेन 10 सितंबर को शुरू</strong><p>अगर आप ट्रेन के दिन 2 पर चढ़ते हैं, तो तत्काल की तारीख 9 सितंबर होगी। AC के लिए 10 बजे, Non-AC के लिए 11 बजे। केवल अपनी बोर्डिंग तारीख से एक दिन घटाने पर गलत दिन मिल सकता है।</p></div>
<h2>समय से पहले क्या तैयार रखें?</h2><ul><li>ट्रेन नंबर, स्टेशन, यात्रा की तारीख और श्रेणी जाँचें।</li><li>IRCTC पर खाते और आवश्यक प्रमाणीकरण की स्थिति पहले जाँचें।</li><li>भुगतान का तरीका तैयार रखें, लेकिन OTP या भुगतान जानकारी इस कैलकुलेटर पर न दें।</li><li>रिमाइंडर कैलेंडर में जोड़ें और सूचना अनुमति जाँचें।</li></ul>
<p>रेल मंत्रालय ने जुलाई 2025 से ऑनलाइन तत्काल में आधार प्रमाणीकरण और OTP संबंधी बदलाव घोषित किए थे। <a href="{AUTH}">आधिकारिक सूचना पढ़ें</a> और बुकिंग के समय IRCTC द्वारा माँगे गए चरण पूरे करें।</p>
<h2>रिमाइंडर का अर्थ</h2><p>RailDate डाउनलोड करने योग्य कैलेंडर इवेंट बनाता है। यह टिकट नहीं खरीदता, सीट नहीं रोकता और IRCTC लॉगिन नहीं करता। opening time पर भी सीट उपलब्ध न हो सकती है। अगर समय बीत चुका है, भविष्य के लिए गलत रिमाइंडर बनाने से बचाने के लिए बटन बंद रहेगा।</p>'''),
        ('train-origin-date-guide/','बोर्डिंग तारीख और ट्रेन की शुरुआती तारीख','बीच के स्टेशन से चढ़ने पर एक दिन का फर्क आपकी बुकिंग की तारीख बदल सकता है।',f'''
<h2>दो तारीखें अलग क्यों होती हैं?</h2><p>लंबी दूरी की ट्रेन रात में शुरू होकर अगले दिन आपके स्टेशन पहुँच सकती है। आपकी यात्रा तारीख वह दिन है जब आप चढ़ते हैं; शुरुआती तारीख वह दिन है जब वही ट्रेन अपने पहले स्टेशन से चली। RailDate दोनों को अलग दिखाता है।</p>
<div class="example"><strong>एक साधारण उदाहरण</strong><p>ट्रेन 10 नवंबर 2026 को रात 10 बजे शुरू होती है। आप 11 नवंबर को सुबह 6 बजे चढ़ते हैं। कैलकुलेटर में यात्रा 11 नवंबर और बोर्डिंग दिन 2 चुनें। शुरुआती तारीख 10 नवंबर होगी।</p><p>इस उदाहरण में सामान्य बुकिंग 11 सितंबर को और तत्काल 9 नवंबर को खुलने की गणना होगी।</p></div>
<h2>कौन-सा दिन चुनें?</h2><ul><li><strong>दिन 1:</strong> ट्रेन के शुरुआती स्टेशन वाली तारीख को ही चढ़ेंगे।</li><li><strong>दिन 2:</strong> शुरुआती तारीख के अगले दिन चढ़ेंगे।</li><li><strong>दिन 3:</strong> शुरुआती तारीख के दो दिन बाद चढ़ेंगे।</li></ul><p>यह दिनों का कैलेंडर फर्क है, यात्रा में बीते पूरे 24 घंटे नहीं। उदाहरण में केवल 8 घंटे बीते हैं, फिर भी तारीख बदलने से दिन 2 है।</p>
<h2>दिन संख्या कहाँ मिलेगी?</h2><p>उसी ट्रेन की आधिकारिक समय-सारणी में शुरुआती स्टेशन और अपने बोर्डिंग स्टेशन की दिन संख्या देखें। अनुमान से चयन न करें। कैलकुलेटर आपके ट्रेन नंबर की समय-सारणी अपने आप नहीं पढ़ता।</p>
<h2>स्रोत और सीमा</h2><p><a href="{ORIGIN}">IRCTC की opening-day परिभाषा</a> शुरुआती स्टेशन की तारीख इस्तेमाल करती है। इस पुराने पेज का 120 दिन वाला उल्लेख नई <a href="{ARP}">60 दिन की सूचना</a> से बदला गया है। <a href="{TATKAL}">तत्काल FAQ</a> भी शुरुआती स्टेशन के आधार पर तारीख बताता है। विशेष ट्रेनों की अवधि IRCTC पर जाँचें।</p>'''),
        ('about/','RailDate के बारे में','बुकिंग तारीख समझने और यात्रा की तैयारी के लिए एक स्वतंत्र वेबसाइट।','''<h2>हम क्या करते हैं?</h2><p>RailDate सामान्य अग्रिम और तत्काल टिकट बुकिंग की opening date निकालता है। इसका मकसद बोर्डिंग तारीख, ट्रेन की शुरुआती तारीख और बुकिंग समय का फर्क साफ दिखाना है। यात्री की पहचान या टिकट विवरण लिए बिना यह गणना ब्राउज़र में होती है।</p><h2>जानकारी कैसे तैयार होती है?</h2><p>गाइड में रेलवे और IRCTC के स्रोत दिए गए हैं। उदाहरण गणना समझाने के लिए बनाए गए हैं; वे किसी ट्रेन की लाइव समय-सारणी नहीं हैं। समीक्षा तारीख बताती है कि सामग्री कब जाँची गई, यह लाइव रेलवे अपडेट नहीं है।</p><h2>स्वतंत्र सेवा</h2><p>RailDate को Yashwant Verma संचालित करते हैं। यह IRCTC या भारतीय रेल की आधिकारिक सेवा नहीं है। हम सीट उपलब्धता, टिकट बुकिंग, भुगतान या PNR सेवा उपलब्ध नहीं कराते।</p><h2>सुधार</h2><p>कोई गणना गलत लगे तो संपर्क पेज पर दिए विकल्प से यात्रा तारीख, दिन संख्या और चुना गया मोड बताएँ। यात्री की निजी जानकारी भेजने की जरूरत नहीं है।</p>'''),
        ('contact/','संपर्क और सुधार','कैलकुलेटर की गलती या वेबसाइट संबंधी सवाल बताएँ।',f'''<h2>वेबसाइट संचालक</h2><p>Yashwant Verma · RailDate</p><p>{contact}</p><p>{'वेबसाइट संबंधी सवाल ऊपर दिए ईमेल पर भेज सकते हैं।' if email else 'ऊपर संचालक का सार्वजनिक GitHub प्रोफ़ाइल है। इस समय अलग सपोर्ट ईमेल प्रकाशित नहीं है।'}</p><h2>गलत परिणाम की जानकारी</h2><p>यात्रा तारीख, ट्रेन का बोर्डिंग दिन, अग्रिम या तत्काल विकल्प और अपेक्षित परिणाम बताएँ। गलती की तस्वीर भेजें तो यात्री नाम, PNR, आधार और भुगतान विवरण हटा दें।</p><h2>टिकट या रिफंड की समस्या?</h2><p>RailDate टिकट जारी नहीं करता और बुकिंग खाते तक इसकी पहुँच नहीं है। टिकट, रिफंड और भुगतान सहायता के लिए <a href="https://www.irctc.co.in/nget/train-search">आधिकारिक IRCTC वेबसाइट</a> के सहायता विकल्प इस्तेमाल करें।</p>'''),
        ('privacy/','गोपनीयता नीति','जानें कि गणना, रिमाइंडर और वेबसाइट उपयोग में कौन-सी जानकारी शामिल होती है।',privacy(hi,email,ads,publisher,contact)),
        ('terms/','उपयोग की शर्तें और अस्वीकरण','RailDate की भूमिका और गणना की सीमाएँ।','''<h2>सेवा का उद्देश्य</h2><p>RailDate यात्रा की योजना के लिए सामान्य तारीख गणना देता है। यह टिकट नहीं बेचता, सीट आरक्षित नहीं करता और भुगतान नहीं लेता। सभी समय IST में हैं।</p><h2>अंतिम जाँच</h2><p>बुकिंग से पहले IRCTC पर ट्रेन, कोटा, तारीख और उपलब्धता जाँचें। विशेष ट्रेनों के नियम, आरक्षण अवधि और परिचालन में बदलाव हो सकते हैं। दिखाई गई opening date सीट मिलने या आखिरी समय तक बुकिंग खुली रहने की गारंटी नहीं है।</p><h2>स्वतंत्रता</h2><p>IRCTC और भारतीय रेल के नाम सिर्फ संबंधित सेवाओं की पहचान के लिए हैं। उनसे संबद्धता या आधिकारिक अनुमोदन का दावा नहीं है।</p><h2>सुरक्षित उपयोग</h2><p>यहाँ लॉगिन, OTP, आधार, बैंक विवरण या यात्री की पहचान न दें। रिमाइंडर डाउनलोड करने के बाद उसे कैलेंडर में जोड़ना और सूचना चालू करना आपकी जिम्मेदारी है।</p><h2>सुधार और बदलाव</h2><p>गलती मिले तो संपर्क पेज से बताएँ। नियम या वेबसाइट सुविधा बदलने पर सामग्री संशोधित हो सकती है।</p>''')]
    return [
    ('advance-booking-guide/','The 60-day train booking rule, explained','How to count the days, find the opening time and recognise the exceptions.',f'''
<h2>Start with calendar days</h2><p>The standard advance reservation period is 60 days, excluding the journey day. This replaced the previous 120-day period from 1 November 2024. Certain daytime services and special quotas use different windows. The <a href="{ARP}">Ministry of Railways announcement</a> explains those exceptions.</p>
<h2>Work backwards from the train’s starting date</h2><ol><li>Find when your train departs its first station.</li><li>Subtract 60 calendar days from that date.</li><li>Use 8:00 AM IST as the standard opening-day time, then verify your train and quota on IRCTC.</li></ol>
<div class="example"><strong>Example: a train starting on 10 November 2026</strong><p>Subtracting 60 days gives 11 September 2026. The standard opening time is 8:00 AM IST. Subtracting two months instead would give 10 September, which is a day too early.</p></div>
<h2>Why “two months before” is unreliable</h2><p>Months have different lengths. For example, 60 days before 30 April 2027 is 1 March 2027. A calendar-day calculation handles the end of a month and leap years without estimating. RailDate uses date arithmetic rather than a fixed month offset.</p>
<h2>What the “today” strip means</h2><p>The upper strip shows the furthest train-origin departure date whose standard opening time has passed. Before 8:00 AM IST, the new 60th-day date has not opened yet, so the displayed boundary stays one day earlier. It is a planning boundary, not a list of available trains.</p>
<h2>When to double-check</h2><p>A special train, a shorter reservation period or a different quota can change the applicable rule. The calculator cannot confirm seats, chart preparation or booking cut-offs. Check those on the official booking screen.</p><p><a href="{ORIGIN}">IRCTC’s opening-day definition</a> supports the 8:00 AM time and train-origin basis. That older page still mentions 120 days; RailDate uses the newer 60-day announcement for the reservation period.</p>'''),
    ('tatkal-booking-guide/','Tatkal booking date and time','Understand the day-before rule, class timings and what to prepare before opening.',f'''
<h2>Find the date first, then the time</h2><p>Tatkal opens one day before the train departs its originating station. Opening times are 10:00 AM IST for AC and 11:00 AM IST for non-AC. Availability depends on the train, class and station pair. See the <a href="{TATKAL}">official IRCTC Tatkal FAQ</a>.</p>
<div class="table-wrap"><table><thead><tr><th>Booking</th><th>Opening date</th><th>Time in IST</th></tr></thead><tbody><tr><td>AC Tatkal</td><td>Train-origin date minus 1 day</td><td>10:00 AM</td></tr><tr><td>Non-AC Tatkal</td><td>Train-origin date minus 1 day</td><td>11:00 AM</td></tr></tbody></table></div>
<div class="example"><strong>Example: boarding on 11 September, train starts on 10 September</strong><p>Select 11 September as your journey and Day 2 as your boarding day. Tatkal is calculated for 9 September: 10:00 AM for AC or 11:00 AM for non-AC.</p></div>
<h2>A practical preparation list</h2><ul><li>Confirm the train number, boarding station, journey date and class.</li><li>Check your IRCTC account and required authentication ahead of time.</li><li>Keep your preferred payment method ready on the official booking service.</li><li>Import the calendar reminder and check notification permissions.</li></ul>
<p>The Ministry announced Aadhaar authentication and OTP changes for online Tatkal bookings in July 2025. Read the <a href="{AUTH}">official authentication notice</a> and follow the requirements shown by IRCTC when booking.</p>
<h2>What a reminder can do</h2><p>The downloaded calendar event helps you remember the opening time. It does not sign in, reserve a seat or purchase a ticket. A reminder cannot guarantee availability. If the opening time has already passed, RailDate disables the future-reminder button instead of creating a misleading alert.</p>'''),
    ('train-origin-date-guide/','Your boarding date is not always the train’s starting date','A midnight crossing can move your booking opening date by a full calendar day.',f'''
<h2>Two dates, one train</h2><p>A long-distance train can leave its first station in the evening and reach your station the following morning. Your journey date is when you board. Its origin date is when that same train started. RailDate shows both so you can check the assumption.</p>
<div class="example"><strong>Example: 10:00 PM departure, 6:00 AM boarding</strong><p>A train starts on 10 November 2026 at 10:00 PM. You board on 11 November at 6:00 AM. Enter 11 November and choose Day 2. The train-origin date becomes 10 November.</p><p>For this example, the standard advance opening date is 11 September; the Tatkal opening date is 9 November.</p></div>
<h2>Choose the timetable day</h2><ul><li><strong>Day 1:</strong> you board on the same calendar date as the train starts.</li><li><strong>Day 2:</strong> you board on the next calendar date.</li><li><strong>Day 3:</strong> you board two calendar dates after the train starts.</li></ul><p>These are calendar dates, not completed 24-hour periods. Only eight hours pass in the example, but the midnight crossing makes it Day 2.</p>
<h2>Where to check</h2><p>Look at the official timetable for the exact train. Compare the day numbers at the originating and boarding stations. RailDate does not fetch train schedules; the boarding-day value is your input. If you are unsure, verify it before relying on the reminder.</p>
<h2>Source and scope</h2><p><a href="{ORIGIN}">IRCTC’s opening-day definition</a> uses the originating station. Its old 120-day wording is superseded by the newer <a href="{ARP}">60-day reservation announcement</a>. The <a href="{TATKAL}">Tatkal FAQ</a> also uses the train-origin date. Train-specific exceptions still need checking on IRCTC.</p>'''),
    ('about/','About RailDate','An independent planning tool for understanding when train booking opens.','''<h2>A clearer starting point for your journey</h2><p>RailDate calculates standard advance and Tatkal opening dates. It makes the distinction between your boarding date and the train’s starting date visible, and gives you a calendar event to help remember the result.</p><h2>How the information is prepared</h2><p>Booking guides link to Railway and IRCTC sources. Worked examples explain the arithmetic; they are not live train schedules. The review date records when the content was checked, not a live connection to railway updates.</p><h2>Who operates it?</h2><p>RailDate is operated by Yashwant Verma. It is independent and is not affiliated with or endorsed by IRCTC or Indian Railways. It does not provide ticket booking, payments, PNR status or live seat availability.</p><h2>Help improve a calculation</h2><p>If a result looks wrong, use the contact page and describe the journey date, boarding day and selected booking mode. There is no need to share passenger details.</p>'''),
    ('contact/','Contact & corrections','Report a calculator issue or ask a question about this website.',f'''<h2>Website operator</h2><p>Yashwant Verma · RailDate</p><p>{contact}</p><p>{'Send website questions to the email above.' if email else 'The link above is the operator’s public GitHub profile. A dedicated support email has not been published yet.'}</p><h2>Reporting a calculation</h2><p>Include your selected date, boarding day, advance or Tatkal mode, and the result you expected. If you share a screenshot, remove passenger names, PNR, Aadhaar and payment details.</p><h2>Ticket or refund help</h2><p>RailDate does not issue tickets and cannot access your bookings. For payment, cancellation or refund support, use the help options on the <a href="https://www.irctc.co.in/nget/train-search">official IRCTC website</a>.</p>'''),
    ('privacy/','Privacy policy','What happens to calculator inputs, reminders and website usage information.',privacy(hi,email,ads,publisher,contact)),
    ('terms/','Terms & disclaimer','The purpose and limits of RailDate’s planning calculations.','''<h2>Planning information</h2><p>RailDate provides date calculations for journey planning. It does not sell tickets, reserve seats, take payments or connect to your IRCTC account. All booking times are in IST.</p><h2>Verify before booking</h2><p>Check the exact train, quota, journey date and availability on IRCTC. Special services, reservation periods and operating arrangements can change. An opening date does not guarantee a seat or that booking remains possible up to departure.</p><h2>Independent website</h2><p>IRCTC and Indian Railways names identify the services being discussed. No affiliation, official status or endorsement is claimed.</p><h2>Safe use</h2><p>Do not enter passwords, OTPs, Aadhaar numbers, bank details or passenger identities here. You are responsible for importing downloaded reminders and enabling calendar notifications.</p><h2>Changes and corrections</h2><p>Report suspected errors using the contact page. Information may be revised when rules or features change.</p>''')]

def privacy(hi,email,ads,publisher,contact):
    if hi:
        adtext='इस संस्करण में Google AdSense विज्ञापन चालू हैं। Google और उसके भागीदार विज्ञापन दिखाने, धोखाधड़ी रोकने और मापने के लिए कुकी तथा अन्य पहचानकर्ता इस्तेमाल कर सकते हैं। जहाँ आवश्यक हो, सहमति संदेश में विकल्प चुनें और वहीं से बदलें।' if ads else 'इस संस्करण में विज्ञापन और analytics tracking scripts बंद हैं। AdSense खाता सत्यापन का मेटा टैग मौजूद हो सकता है; वह स्वयं विज्ञापन स्क्रिप्ट नहीं चलाता। विज्ञापन शुरू होने पर यह नीति अपडेट होगी।'
        return f'''<h2>कैलकुलेटर की जानकारी</h2><p>यात्रा तारीख, दिन संख्या और श्रेणी की गणना ब्राउज़र में होती है। वेबसाइट इन्हें किसी बुकिंग सर्वर पर नहीं भेजती। हमारे कैलकुलेटर में खाता, यात्री विवरण, PNR, OTP या भुगतान लेने की सुविधा नहीं है।</p><h2>कैलेंडर और कॉपी</h2><p>रिमाइंडर बटन आपके उपकरण पर .ics फ़ाइल डाउनलोड करता है। उसे दूसरे कैलेंडर में जोड़ने पर उस सेवा की नीति लागू होती है। कॉपी बटन दबाने पर दिख रही बुकिंग जानकारी आपके क्लिपबोर्ड में जाती है।</p><h2>होस्टिंग और संपर्क</h2><p>होस्टिंग प्रदाता अनुरोध पूरा करने और सुरक्षा के लिए IP पता, ब्राउज़र और अनुरोध का समय जैसे सामान्य सर्वर लॉग संसाधित कर सकता है। संपर्क करने पर आपके द्वारा भेजी गई जानकारी उस माध्यम पर प्राप्त होती है।</p><h2>विज्ञापन और कुकी</h2><p>{adtext}</p><p>Google डेटा के उपयोग की जानकारी <a href="https://policies.google.com/technologies/partner-sites">Google partner sites policy</a> में है। विज्ञापन विकल्प <a href="https://myadcenter.google.com/">My Ad Center</a> में मिलते हैं।</p><h2>बाहरी लिंक</h2><p>IRCTC, GitHub और अन्य बाहरी सेवाओं की अपनी नीतियाँ हैं। RailDate उन सेवाओं पर आपकी गतिविधि नियंत्रित नहीं करता।</p><h2>गोपनीयता संबंधी सवाल</h2><p>संचालक Yashwant Verma से संपर्क: {contact}। संवेदनशील पहचान या भुगतान जानकारी न भेजें।</p>'''
    adtext='Google AdSense is enabled in this version. Google and its partners may use cookies and other identifiers to serve and measure ads and prevent fraud. Where required, use the consent message to choose or change your preferences.' if ads else 'Advertising and analytics tracking scripts are disabled in this version. An AdSense account-verification meta tag may be present; it does not itself run an advertising script. This policy will be updated when advertising is enabled.'
    return f'''<h2>Calculator inputs</h2><p>Your date, boarding day and class are processed in your browser. The calculator does not send those inputs to a booking server. There are no accounts, passenger forms, PNR lookups, OTP fields or payments.</p><h2>Reminders and clipboard</h2><p>The reminder button downloads an .ics calendar file to your device. Importing it into another calendar is governed by that service’s policy. Clicking Copy date writes the displayed booking information to your clipboard.</p><h2>Hosting and correspondence</h2><p>The hosting provider may process ordinary request data such as IP address, browser information and request time to deliver and secure the site. If you contact the operator, the information you send is received through that communication service.</p><h2>Advertising and cookies</h2><p>{adtext}</p><p>See <a href="https://policies.google.com/technologies/partner-sites">how Google uses data on partner sites</a> and manage ad preferences in <a href="https://myadcenter.google.com/">My Ad Center</a>.</p><h2>External services</h2><p>IRCTC, GitHub and other linked sites have their own privacy policies. RailDate does not control what happens on those sites.</p><h2>Privacy questions</h2><p>Contact the operator, Yashwant Verma: {contact}. Do not send sensitive identity or payment information.</p>'''
